---
services:
  dockerify-android:
    container_name: dockerify-android
    image: shmayro/dockerify-android:latest
    build:
      context: .
    ports:
      - "5555:5555"
    volumes:
      - ${data_path}:/data
      - ${extras_path}:/extras
    environment:
      DNS: one.one.one.one
      RAM_SIZE: ${RAM_SIZE}
      # Optional screen resolution in WIDTHxHEIGHT format
      SCREEN_RESOLUTION: ${SCREEN_RESOLUTION}
      # Optional screen density (dpi)
      #SCREEN_DENSITY: 227
      ROOT_SETUP: ${ROOT_SETUP} # set to 1 to enable rooting
      GAPPS_SETUP: ${GAPPS_SETUP} # set to 1 to install PICO GAPPS
    privileged: ${privileged_android}
    devices:
      - /dev/kvm

  scrcpy-web:
    container_name: scrcpy-web
    restart: unless-stopped
    image: shmayro/scrcpy-web:latest
    privileged: ${privileged_scrcpy}
    ports:
      - 8000:8000
    depends_on:
      dockerify-android:
        condition: service_healthy
    command: >
      sh -c "
        adb connect dockerify-android:5555 &&
        npm start
      "

